[project]
name = "main"
version = "0.0.0"
dependencies = [
    "beautifulsoup4",
    "lxml",
    "requests",
    "python-dateutil"
]
requires-python = ">=3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
